### ISSUE TITLE
Failed to run `config` for none-ls.nvim

### ISSUE THREAD

**Issue by afreisinger** [dobval/NvChad-python-config#1]
Hello ! Excellent setup, but I have the following problem
"Error running `config` for null-ls.nvim
/.config/nvim/lua/custom/configs/null-ls.lua:6: Attempt to index field 'built-in' (a null value)

# stack trace:
  - ~/.config/nvim/lua/custom/configs/null-ls.lua:6
  - /opt/nvim-linux64/share/nvim/runtime/filetype.lua:25
  - /opt/nvim-linux64/share/nvim/runtime/filetype.lua:24
"
Any ideas?
thank you so much

**Comment by dobval** [comment]
Noticed this today too after updating. Will have to look into it, thanks.

**Comment by dobval** [comment]
Updated the config file to new syntax ".builtin" to ".builtins", should be fixed.
