### ISSUE TITLE
Readme not compatibile with NvChad v2.5

### ISSUE THREAD

**Issue by amrutadotorg** [dobval/NvChad-python-config#2]
It would be great to update the readme for nvchad 2.5 (no custom [config](https://nvchad.com/news/v2.5_release/))

for example in 2.5 this will not work:
git clone https://github.com/dobval/NvChad-python-config.git ~/.config/nvim/lua/custom

**Comment by dobval** [comment]
Thanks, will look into it soon

**Comment by sudanking** [comment]
+1
